apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app-container
          image: akshathphillipspersonal/swe645-hw3:v6 # Your Spring app image
          ports:
            - containerPort: 8081 # Port your Spring app listens on
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 8081 # Port you want to expose externally (on the Node)
      targetPort: 8081 # Port your Spring app listens on