apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw2-cluster-deployment-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw2-app-label
  template:
    metadata:
      labels:
        app: hw2-app-label
    spec:
      containers:
      - name: hw2-container
        image: akshathphillipspersonal/swe645:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hw2-cluster-deployment
spec:
  type: NodePort
  selector:
    app: hw2-app-label
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
