apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw2-cluster-deployment-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw2-app-label
  template:
    metadata:
      labels:
        app: hw2-app-label
    spec:
      containers:
      - name: hw2-container
        image: akshathphillipspersonal/swe645:v21
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: hw2-cluster-deployment
spec:
  type: NodePort
  selector:
    app: hw2-app-label
  ports:
    - protocol: TCP
      port: 8080   # <-- This can remain the same. This is the port where you'd access the service from outside the cluster.
      targetPort: 8080   # <-- This should be the same as your containerPort because this is where traffic will be forwarded to.
      name: http
