pipeline {
    agent any

    tools {
        maven 'Maven 3.6.3'
        jdk 'Java 17'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/akshathphillips/SWE-645'
            }
        }

        stage('Build WAR') {
            steps {
                dir('HW1-Part2') {
                    sh 'mvn clean install'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    def tagName = "v" + env.BUILD_NUMBER // using Jenkins build number as an example
                    def dockerImageName = "akshathphillipspersonal/swe645:${tagName}"
                    
              
                    def dockerImage = docker.build(dockerImageName)
                    
                
                    env.DOCKER_TAG_NAME = tagName
                }
            }
          }

        stage('Push Docker Image') {
            steps {
                script {
                    sh "docker push akshathphillipspersonal/swe645:${env.DOCKER_TAG_NAME}"
                }
            }
        }
    }
}
