pipeline {
    agent any
    
    environment {
        DOCKER_CREDENTIALS = 'af3bf4df-c402-4c86-8367-03bb2c9e5884'
    }

    tools {
        maven 'Maven 3.6.3'
        jdk 'Java 17'
    }
    
    stages {
        stage('Docker Login') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: "${DOCKER_CREDENTIALS}", passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                        sh "docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}"
                    }
                }
            }
        }
    }

    stages {
        // stage('Checkout') {
        //     steps {
        //         git 'https://github.com/akshathphillips/SWE-645'
        //     }
        // }

        stage('Build WAR') {
            steps {
                dir('HW1-Part2') {
                     script {
                        // Set JAVA_HOME explicitly before the Maven command
                        env.JAVA_HOME = '/usr/lib/jvm/java-17-openjdk-amd64'  // Ensure this path is correct
                    }
                    sh '''
                        echo $JAVA_HOME
                        mvn clean install
                    '''
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('HW1-Part2') {
                    script {
                        def tagName = "v" + env.BUILD_NUMBER // using Jenkins build number as an example
                        def dockerImageName = "akshathphillipspersonal/swe645:${tagName}"
                        
                  
                        def dockerImage = docker.build(dockerImageName)
                        
                    
                        env.DOCKER_TAG_NAME = tagName
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    sh "docker push akshathphillipspersonal/swe645:${env.DOCKER_TAG_NAME}"
                }
            }
        }
    }
}
